# Generated by Django 6.1.1 on 2026-09-26 20:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_id", models.UUIDField()),
                ("worker_id", models.CharField(max_length=64)),
                ("reason", models.TextField()),
                ("previous_status", models.CharField(max_length=16)),
                ("previous_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkerProbe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("released", models.BooleanField(default=True)),
                ("fail_once", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
    ]
