# Generated by Django 6.1.1 on 2026-09-26 22:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Matter",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("public", "Опубликовано"),
                            ("hidden", "Скрыто"),
                        ],
                        default="draft",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "canonical",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merged_matters",
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "permissions": [("reconcile_matter", "Can merge and split matter identities")],
            },
        ),
        migrations.CreateModel(
            name="MatterDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("merge", "Объединение"), ("split", "Разделение")], max_length=8
                    ),
                ),
                ("reason", models.TextField()),
                ("before", models.JSONField()),
                ("after", models.JSONField()),
                ("created_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatterRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("continuation", "Продолжение"),
                            ("joint", "Совместное рассмотрение"),
                            ("alternative", "Альтернативная инициатива"),
                        ],
                        max_length=16,
                    ),
                ),
                ("evidence_url", models.URLField(max_length=2048)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="matters.matterdecision",
                    ),
                ),
                (
                    "from_matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_relations",
                        to="matters.matter",
                    ),
                ),
                (
                    "to_matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relations",
                        to="matters.matter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=2048, unique=True)),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="public_aliases",
                        to="matters.matter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("sejm", "Сейм"),
                            ("rpw", "RPW"),
                            ("rcl", "RCL"),
                            ("wykaz", "Wykaz"),
                        ],
                        max_length=8,
                    ),
                ),
                ("scope", models.CharField(max_length=100)),
                ("external_id", models.CharField(max_length=255)),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identities",
                        to="matters.matter",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="matter",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical", models.F("public_id")), _negated=True),
                name="matter_not_own_canonical",
            ),
        ),
        migrations.AddConstraint(
            model_name="matter",
            constraint=models.CheckConstraint(
                condition=models.Q(("visibility__in", ["draft", "public", "hidden"])),
                name="matter_valid_visibility",
            ),
        ),
        migrations.AddConstraint(
            model_name="matterrelation",
            constraint=models.UniqueConstraint(
                fields=("from_matter", "to_matter", "kind"), name="matter_relation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="matterrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_matter", models.F("to_matter")), _negated=True),
                name="matter_relation_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="matterrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["continuation", "joint", "alternative"])),
                name="matter_relation_valid_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceidentity",
            constraint=models.UniqueConstraint(
                fields=("source", "scope", "external_id"), name="source_identity_natural_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", ""), _negated=True),
                    models.Q(("external_id", ""), _negated=True),
                ),
                name="source_identity_nonempty_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["sejm", "rpw", "rcl", "wykaz"])),
                name="source_identity_valid_source",
            ),
        ),
    ]
