from allauth.mfa.models import Authenticator
from django.contrib.auth.base_user import AbstractBaseUser

def generate_totp_secret(length: int = ...) -> str: ...
def hotp_value(secret: str, counter: int) -> int: ...
def format_hotp_value(value: int) -> str: ...

class TOTP:
    instance: Authenticator
    @classmethod
    def activate(cls, user: AbstractBaseUser, secret: str) -> TOTP: ...
