# Generated by Django 6.1.1 on 2026-09-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_commit", models.CharField(max_length=40)),
                ("dump_sha256", models.CharField(max_length=64)),
                ("source_schema", models.PositiveIntegerField()),
                ("contract_version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField()),
                ("counts", models.JSONField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_commit", "dump_sha256"), name="import_generation_snapshot"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatterEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_key", models.CharField(max_length=255, unique=True)),
                ("provenance", models.CharField(max_length=32)),
                ("observed_at", models.DateTimeField()),
                ("occurred_at", models.DateTimeField(null=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="matters.sourceidentity",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="matters.matter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("payload", models.JSONField()),
                ("semantic_hash", models.CharField(max_length=64)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="ingestion.importgeneration",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="matters.sourceidentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatterFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.TextField()),
                ("bot_status", models.CharField(max_length=32)),
                ("relevant", models.BooleanField(null=True)),
                ("score", models.PositiveSmallIntegerField(null=True)),
                ("category", models.CharField(blank=True, max_length=32)),
                ("document_date", models.DateField(null=True)),
                ("closure_date", models.DateField(null=True)),
                ("content_updated_at", models.DateTimeField()),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="ingestion.importgeneration",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facts",
                        to="matters.matter",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ingestion.sourcesnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActiveImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.importgeneration",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)), name="active_import_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ingestion.importgeneration",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="ingestion.matterevent",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "generation"), name="event_revision_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sourcesnapshot",
            constraint=models.UniqueConstraint(
                fields=("generation", "identity"), name="source_snapshot_per_generation"
            ),
        ),
        migrations.AddConstraint(
            model_name="matterfacts",
            constraint=models.UniqueConstraint(
                fields=("generation", "matter"), name="matter_facts_unique"
            ),
        ),
    ]
