# Generated by Django 6.1.1 on 2026-09-27 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0002_active_import_singleton"),
        ("matters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="importgeneration",
            name="pruned_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("activated", "Activated"),
                            ("unchanged", "Unchanged"),
                            ("already_running", "Already Running"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_kind", models.CharField(blank=True, max_length=64)),
                ("message", models.TextField(blank=True)),
                ("pruned_generations", models.PositiveIntegerField(default=0)),
                (
                    "generation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.importgeneration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("history", "История state переписана"),
                            ("corpus_drop", "Резкое падение корпуса"),
                            ("reconciliation", "Цепочка охватывает несколько дел"),
                            ("absent", "Строка пропала из снимка"),
                            ("invalid", "Снимок отклонён"),
                        ],
                        max_length=16,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("detail", models.TextField()),
                ("opened_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(null=True)),
                ("resolution", models.TextField(blank=True)),
                (
                    "identity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="matters.sourceidentity",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("key",),
                        name="import_issue_open_once",
                    )
                ],
            },
        ),
    ]
