"""Domain models. Pure data + a few pure functions; no I/O here.

Split by area (`enums`, `sejm`, `analysis`, `bill`, `report`); everything is re-exported here so
`from lexinform.models import Bill` keeps working.
"""

from __future__ import annotations

from lexinform.models.analysis import (
    Analysis,
    AnalysisRecord,
    BillContext,
    TokenUsage,
    Triage,
    TriageContext,
    TriageRecord,
    add_usage,
    usage_of,
)
from lexinform.models.bill import (
    Bill,
    Publication,
    StatusChange,
)
from lexinform.models.enums import (
    BILL_DOCUMENT_TYPE,
    PRE_PRINT_PREFIX,
    ApplicantType,
    BillStatus,
    Category,
    DocumentType,
    PublicationKind,
    PublicationStatus,
    SourceKind,
    TextSource,
)
from lexinform.models.report import (
    AnalysisVerdict,
    RunReport,
)
from lexinform.models.sejm import (
    ActInfo,
    Attachment,
    BillAuthors,
    BillSubmission,
    ClubVotes,
    Committee,
    Mp,
    PrintInfo,
    ProcessDetail,
    ProcessSummary,
    Stage,
    TextDocument,
    Vote,
    VotingSummary,
    aggregate_clubs,
    applicant_from_title,
    committee_web_url,
    diff_stages,
    flatten_stages,
    is_pre_print_number,
    latest_text_document,
    print_web_url,
    process_web_url,
    stage_fingerprint,
    submission_pdf_url,
)

__all__ = [
    "ActInfo",
    "Analysis",
    "AnalysisRecord",
    "AnalysisVerdict",
    "ApplicantType",
    "Attachment",
    "BILL_DOCUMENT_TYPE",
    "Bill",
    "BillAuthors",
    "BillContext",
    "BillStatus",
    "BillSubmission",
    "Category",
    "ClubVotes",
    "Committee",
    "DocumentType",
    "Mp",
    "PRE_PRINT_PREFIX",
    "PrintInfo",
    "ProcessDetail",
    "ProcessSummary",
    "Publication",
    "PublicationKind",
    "PublicationStatus",
    "RunReport",
    "SourceKind",
    "Stage",
    "StatusChange",
    "TextDocument",
    "TextSource",
    "TokenUsage",
    "Triage",
    "TriageContext",
    "TriageRecord",
    "Vote",
    "VotingSummary",
    "add_usage",
    "aggregate_clubs",
    "applicant_from_title",
    "committee_web_url",
    "diff_stages",
    "flatten_stages",
    "is_pre_print_number",
    "latest_text_document",
    "print_web_url",
    "process_web_url",
    "stage_fingerprint",
    "submission_pdf_url",
    "usage_of",
]
